// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dfmfnoszduarprphxlgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRmbWZub3N6ZHVhcnBycGh4bGdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3NDM5NDcsImV4cCI6MjA3MDMxOTk0N30.pfGOiI0AZGUDDlHggRdIUXA0AX35hoPtxrdUv7QBcQA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});