// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://scpelwofjvvodpobiujn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNjcGVsd29manZ2b2Rwb2JpdWpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzNzYwODUsImV4cCI6MjA2NDk1MjA4NX0.7j9FvLQ2YzkqhxYxh7pBBrLtNQfyYAuZpapYOR8Q8ng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);